# Generated by Django 5.1.1 on 2024-09-24 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guardias', '0002_objetivo_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('tipoNovedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guardias.tiponovedad')),
            ],
        ),
    ]
