# Generated by Django 5.1.1 on 2024-09-24 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guardias', '0003_novedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='fechaNovedad',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='novedad',
            name='horaNovedad',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
