# Generated by Django 5.1.1 on 2024-09-25 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0004_alter_empresa_contacto_alter_empresa_cuit_and_more'),
        ('Guardias', '0007_alter_novedad_fechahoraalta'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='empresa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Empresa.empresa'),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='nombre',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='ubicacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Guardias.ubicacion'),
        ),
    ]
