# Generated by Django 5.1.1 on 2024-10-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guardias', '0009_alter_objetivo_nombre_alter_tiponovedad_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='nombre',
            field=models.CharField(default='', max_length=150),
        ),
    ]
