# Generated by Django 5.1.1 on 2024-09-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0002_alter_empresa_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='nombre',
        ),
        migrations.AddField(
            model_name='empresa',
            name='contacto',
            field=models.CharField(default='0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cuit',
            field=models.CharField(default='0000000', max_length=11),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razonSocial',
            field=models.CharField(default='0000000', max_length=200),
        ),
        migrations.AddField(
            model_name='empresa',
            name='titular',
            field=models.CharField(default='0000000', max_length=150),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(default='0000000', max_length=200),
        ),
    ]
