# Generated by Django 5.1.1 on 2024-09-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0003_remove_empresa_nombre_empresa_contacto_empresa_cuit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='contacto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cuit',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razonSocial',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='titular',
            field=models.CharField(default='', max_length=150),
        ),
    ]
